### ISSUE TITLE
TPP on arxiv 

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#124]

**Comment by hasan3050** [comment]
This is updated in our website. You can close it @mosharaf

**Comment by mosharaf** [comment]
Updated

**Comment by hasan3050** [comment]
I think that's from my end. The title (both in the paper and the website is with `CXL-Enabled`). I can send another pull request with the updated one for our website

**Comment by mosharaf** [comment]
No. It's supposed to fix the case by itself.

**Comment by mosharaf** [comment]
Created #127. Closing this one.
