### ISSUE TITLE
Swan (Flamingo) - arXiv in Pubs

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#128]
https://arxiv.org/abs/2206.04687

**Comment by mosharaf** [comment]
@singam-sanjay Upload it asap.

**Comment by singam-sanjay** [comment]
👍

**Comment by singam-sanjay** [comment]
Please check https://github.com/SymbioticLab/SymbioticLab.github.io/pull/131
