### ISSUE TITLE
Sorting order issues

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#140]
Because @Aetf  and @jimmyyou both put in August as their dissertation completion time, their theses show up in arbitrary order in the pubs page. 

Ignore?

**Comment by Aetf** [comment]
Well, technically we do have the same completion time. I'm okay with changing mine to May, though.

**Comment by mosharaf** [comment]
I thought I'd ask you to make June (which I think is more correct), but the fundamental problem would still be same. If both of you did submit in August, the ordering would be random. So maybe ignoring is fine. There is an ordered list in the people page anyway.

**Comment by Aetf** [comment]
Ignore then. Closing this.
