### ISSUE TITLE
Auxo in Pubs

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#209]
Congrats Amber!

**Comment by jaywonchung** [comment]
And remove the PDF for the 2022 Auxo entry? That one's an arXiv paper but somehow has a PDF uploaded (I missed that in the PR review). Ref: #214

**Comment by mosharaf** [comment]
There are several like this, not just Auxo

**Comment by mosharaf** [comment]
@AmberLJC Please send a pull request.  Also, remember to update the arxiv version

**Comment by insujang** [comment]
CR pull request has been merged. @AmberLJC Please close the issue if you updated the arxiv version.

**Comment by AmberLJC** [comment]
Thanks Insu, I might not have the permission to close the issue, please close it for me. The arxiv version is updated
