### ISSUE TITLE
Vulcan in pubs

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#239]

**Comment by yiwenzhang92** [comment]
Do we want to upload the version before the camera ready or leave the paper link as an empty link? (I prefer the latter)

**Comment by mosharaf** [comment]
We've been doing after camera-ready. So, neither I guess. This is a placeholder so that we don't forget it.

**Comment by yiwenzhang92** [comment]
Got it

**Comment by mosharaf** [comment]
@yiwenzhang92 please address it when you get a chance. Thanks.

**Comment by yiwenzhang92** [comment]
Created a pull request (https://github.com/SymbioticLab/SymbioticLab.github.io/pull/247)
