### ISSUE TITLE
Font size is too large

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#25]
Especially so when we're looking at a lot of text like in the project page. It's perhaps a bit too large in general.

**Comment by Aetf** [comment]
The theme applies 1.25x font size when on large screen resolution.

On the left is original, and right with that disabled.
![image](https://user-images.githubusercontent.com/1519759/96543051-87918f00-1271-11eb-891a-ee44f7a52d9d.png)

If the right one looks OK I can go ahead and commit the change

**Comment by Aetf** [comment]
Or, perhapes it's the line-height that makes you feel so.

Top is the original, bottom with both font size and line height set to normal.
![image](https://user-images.githubusercontent.com/1519759/96543346-2ae2a400-1272-11eb-8e71-e6acb6ad7350.png)

**Comment by mosharaf** [comment]
The last one with tighter lines are better. The spacing between words are a bit odd. Maybe we should go with left-aligned instead of justified.

**Comment by mosharaf** [comment]
Also, getting rid of that 1.25X is good too.
