### ISSUE TITLE
Add logo in site header

### ISSUE THREAD

**Issue by Aetf** [SymbioticLab/SymbioticLab.github.io#26]
Need to find a good place and layout.

Maybe need to add a new custom file.

**Comment by Aetf** [comment]
Not sure how I can fit a logo into the current design...

The current design
![image](https://user-images.githubusercontent.com/1519759/97772194-14aed080-1b1b-11eb-9972-62b32b1b2f5c.png)


Directly adding a logo looks weird
![image](https://user-images.githubusercontent.com/1519759/97772166-c39edc80-1b1a-11eb-83ca-b383dd3d7717.png)

Shrink the padding + remove lines. This is better but I kind of like the design of the lines
![image](https://user-images.githubusercontent.com/1519759/97772182-f2b54e00-1b1a-11eb-8436-94f8c57c917d.png)

Move the lines around
![image](https://user-images.githubusercontent.com/1519759/97772332-660b8f80-1b1c-11eb-9e91-552b5d8ffcb5.png)

**Comment by Romero027** [comment]
Personally, I like the third one(no lines).
