### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#27]
Some sort of card-based news could be great. Basically, the titles from https://www.mosharaf.com/blog/ since end of 2015 - early 2016 can be used to fill things up initially.

**Comment by mosharaf** [comment]
The cards can be prefaced by the fig from projects page and the initial text. (Just a thought)

**Comment by mosharaf** [comment]
Other news items would be whenever one of us presents in a conference etc.

**Comment by Romero027** [comment]
I was thinking maybe we can have 1) A short description of our lab and our research directions. 2) recent news and 3) a group picture?

**Comment by Romero027** [comment]
and maybe we can add a "featured project" section.

**Comment by Aetf** [comment]
New front page is now implemented
