### ISSUE TITLE
Fix color theme

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#30]
We should consider using orange and black to be consistent everywhere. Jimmy has the color codes that we used for the logo.

**Comment by Aetf** [comment]
What part do you think should be changed? IMHO not too many parts need color anyway.

The favicon and other less noticed places like Android Chrome header panel color and MS Windows Modern tile color are already set to the correct color `#fe6600`.

One possible place is the badge in publications. I just picked purple for "new" and red for others, so it could use some improvement.

Maybe what is needed is just proper documentation of this so in the future when we creating figures for posts the correct color is used.

**Comment by Aetf** [comment]
Site logo font and color are now correct.
