### ISSUE TITLE
Kayak in pubs

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#33]

**Comment by mosharaf** [comment]
It's not showing up on https://symbioticlab.org/publications/ for me.

**Comment by Aetf** [comment]
The conference is in April, and by default entries in the future is hidden

**Comment by mosharaf** [comment]
Maybe we should fix it? It should be visible as soon as it's added so that people can readily find it. Otherwise, people won't find the paper until the conference happen which isn't ideal.

**Comment by Aetf** [comment]
At first, I added that as a way to prevent accidental uploading draft versions before submission. But since in practice no one really adds paper that early I guess I can remove the filtering.

**Comment by mosharaf** [comment]
Sounds good. Papers should be uploaded after camera-ready deadline.

**Comment by mosharaf** [comment]
Ping!

**Comment by mosharaf** [comment]
Closing this one. Issue #57 covers it.
