### ISSUE TITLE
Make the frontpage news scrollable instead of paginated

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#46]
Either infiniscroll or loaded N at a time by clicking a more button, which will give a more continuous feeling over time.

**Comment by Aetf** [comment]
It's not easy to implement infiniscroll or partial load (they are basically the same) on a static site.

I believe the biggest issue currently is that the pagination jumps around and the scroll position resets when clicking the link. These are all fixed now.
