### ISSUE TITLE
Javascript and CSS doesn't load on going to a page. 

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#48]
Reloading the page with CMD+R fixes it.

![image](https://user-images.githubusercontent.com/232966/105513473-59708080-5ca0-11eb-8cd8-081394953fd5.png)

The same problem happens (less often) when clicking a filter. I believe that's also a JS/CSS loading issue.

Perhaps we can load them at the beginning of the page load process?

**Comment by Aetf** [comment]
I'm aware of this issue, the instant page switch breaks the conditional css and js loading for filters.
