### ISSUE TITLE
Pub should be visible in publish as soon as it's available

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#57]
Currently, it waits for the conference date to come which is unnecessarily slowing things down.

**Comment by mosharaf** [comment]
@Aetf I couldn't find the script where this is. Is it in our repo or somewhere upstream?

**Comment by Aetf** [comment]
It's here: https://github.com/Aetf/hexo-next-publist. I already take note of this https://github.com/Aetf/hexo-next-publist/issues/12.

I kept it as a separate repo so I can share code between the group website and mine.
