### ISSUE TITLE
AE badges

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#71]
It seems every conference is coming up with slightly different names for the same badges. This is annoying because it's crowding our badges dropdown. Let's discuss here a consistent set of names that we can use throughout.

**Comment by Romero027** [comment]
I think we probably should just use "Artifacts Available", "Artifacts Functional", and "Results Reproduced". It looks like SIGCOMM '21 is using these terminologies too(https://conferences.sigcomm.org/sigcomm/2021/cf-artifacts.html). (I'm not sure why SIGCOMM '20 used "Artifact Reusable")

**Comment by Romero027** [comment]
and we can replace "Artifacts Evaluated Functional" with "Artifacts Functional" for mlsys '20

**Comment by mosharaf** [comment]
I'm ok with this ("Artifacts Available", "Artifacts Functional", and "Results Reproduced")

SIGCOMM'20 AE was somewhat rushed. For example, the papers don't really have a badge on them; they are only mentioned on the program page.

**Comment by Romero027** [comment]
What do you think? @fanlai0990 @Aetf I can create a PR to fix the badges.

**Comment by fanlai0990** [comment]
("Artifacts Available", "Artifacts Functional", and "Results Reproduced") Sounds good to me.

**Comment by Aetf** [comment]
Sounds good

**Comment by Romero027** [comment]
okay, will create a PR to fix this soon
