### ISSUE TITLE
Juncheng's Dissertation to Pubs

### ISSUE THREAD

**Issue by mosharaf** [SymbioticLab/SymbioticLab.github.io#89]
Once it's finalized, I think we should keep copies of everyone's dissertations. Congrats again!

**Comment by juncgu** [comment]
Thank you!
@mosharaf, should we add a new "Dissertation" category in "Venue"?

**Comment by mosharaf** [comment]
Yes.

**Comment by juncgu** [comment]
How about we add the "Dissertation" label under the "Technical Reports" category (similar to "arXiv")?

**Comment by mosharaf** [comment]
Yeah, seems better
